### PR TITLE
autofill search google map search done

### PR DESCRIPTION
**Pull request by vinitraj10**
# 5

### CODE REVIEW

**Comment by tomscholz** [comment]
@vinitraj10 Can you explain what you did exactly?

**Comment by vinitraj10** [comment]
Yes i did,i add a default google search map code and i created a api key from there and pasted there i think it's working

**Comment by tomscholz** [comment]
@vinitray10 Take your time :)

**Comment by tomscholz** [comment]
@vinitraj10 Try to make Google Maps related changes inside the map.js file in in js/ folder

**Comment by tomscholz** [comment]
@vinitraj10 Still?

**Pull request closed without merging**
